### ISSUE TITLE
Arbitrary termination conceals unstable EM steps?

### ISSUE THREAD

**Issue by philastrophist** [pmelchior/pygmmis#10] opened 2019-01-20 13:32 UTC
I have found that --for some truncated models-- the log-likelihood decreases immediately from the starting point and EM steps taken by `GMM.fit` can make things worse. 
If I remove the convergence conditions for these models and just run until `maxiter` is reached, the EM steps always result in a lower `logL`. 
I was under the impression that EM is supposed to guarantee that the likelihood increases. 
For the model I use [here](https://gist.github.com/philastrophist/d7aff0810158269424e95b62ea98b4bc) (where green is the ground truth):

![aggressive](https://user-images.githubusercontent.com/14169057/51439612-e4cf6980-1cb4-11e9-8e05-7463a0465ee8.png)

- If I keep the convergence checks, the model doesn't move away from the k-means result (i.e. no steps are taken since the `logL` decreases). This is shown in black
- if I remove the convergence checks but set `maxiter=300`, then I get something that appears reasonable (shown in red).
-But this is arbitrary, if I allow it to continue then it degrades into rubbish (the result after 700 steps more is shown in blue)

So EM appears not to work for this model, the likelihood always decreases despite the fact that I gave it the k-means estimate based on all data, not just the observed.

This doesn't happen for all models. If I use a less aggressive truncation, then the model stablises as it should:
![not-aggressive](https://user-images.githubusercontent.com/14169057/51439670-77700880-1cb5-11e9-9b8a-b5300e4cbcd4.png)

My model is [here](https://gist.github.com/philastrophist/d7aff0810158269424e95b62ea98b4bc) and produces the plots above.

================
I discovered this effect after implementing my own convergence detection technique to deal with problems such as the one I've seen in #11.
The log-likelihood decreases but then goes back up higher than before so the original convergence checks would terminate early.

![logL](https://user-images.githubusercontent.com/14169057/51193356-9438c480-18e0-11e9-92b4-19cedb4b796a.png)

My plan was to fix this with a gradient test (my `feature/convergence` -  #12 ) branch (which also includes tools to visualise what's happening and a backend to store the EMSteps). This method has fixed that problem but it can't solve this one.

Comments and suggestions would be really helpful!

Thanks

**Comment by pmelchior** [comment] 2020-09-04 18:29
duplicate of #11

**Closed as completed by pmelchior** 2020-09-04 18:29 UTC
